M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-04-29T10:25:46+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-29T10:25:46+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X0.3996Y0.7252
X0.3996Y0.2752
M30
