M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-05-07T00:28:05+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-07T00:28:05+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X0.4012Y0.725
X0.4012Y0.275
M30
